resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: BuildNadPush
  displayName: Build and push image
  jobs:  
  - job: Build
    displayName: Build and push
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: ./build.sh
    - task: Docker@2
      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
      displayName: Build an image
      inputs:
        containerRegistry: 'rtuitlab connection by admin'
        repository: 'rtuitlab/motiwade'
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/deploy/Dockerfile'
        buildContext: '$(Build.SourcesDirectory)/deploy'
        tags: |
          $(tag)
          latest
        addPipelineData: false
    - task: SSH@0
      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
      inputs:
        sshEndpoint: 'swarm manager'
        runOptions: 'commands'
        commands: 'docker service update --image rtuitlab/motiwade:$(tag) motiwade_app'
        readyTimeout: '20000'