version: '3.8'

services:
  app:
    build: deploy
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DbType: Postgres
      ConnectionStrings__Postgres: User ID=postgres;Password=password;Server=postgres;Port=5432;Database=learning-dev-db;Integrated Security=true;
    ports:
      - 5501:5501
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432